apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: NodePort
  selector:
    app: kong
  ports:
    - name: proxy       # <-- nom obligatoire
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: admin       # <-- nom obligatoire
      port: 8001
      targetPort: 8001
      nodePort: 30081

---
apiVersion: v1
kind: Service
metadata:
  name: inscription
spec:
  type: ClusterIP
  selector:
    app: inscription
  ports:
    - port: 3001
      targetPort: 3001

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: cotes
# spec:
#   type: ClusterIP
#   selector:
#     app: cotes
#   ports:
#     - port: 3003
#       targetPort: 3003

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: enseignement
# spec:
#   type: ClusterIP
#   selector:
#     app: enseignement
#   ports:
#     - port: 3002
#       targetPort: 3002
